---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: eks-small
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: eks-small
    # TODO: we're temporarily supporting dependency on an existing default storage class
    # on the cluster, this hack will trigger re-queue on Addons until one exists.
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    # The version of Minecraft deployed by this chart is:
    # (catalog requires the -N where N is the package release of the addon)
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.14.4-1"
    appversion.kubeaddons.mesosphere.io/eks-small: "1.14.4"
    # This url is used by kommander to display a link to the documentation
    docs.kubeaddons.mesosphere.io/aws-cli: "https://hub.docker.com/r/mesosphere/aws-cli/dockerfile"
    # These are the raw values for this chart. It is expected that these chart values will be well documented
    # in-line.
    values.chart.helm.kubeaddons.mesosphere.io/eks-small: "https://raw.githubusercontent.com/helm/charts/master/stable/minecraft/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
  requires:
  chartReference:
    chart: stable/eks-small
    version: 1.1.6
    values: |
      ---
      eks-small:
        eula: "TRUE"
        viewDistance: 50

